language: ruby
cache: bundler
branches:
  only:
    - gh-pages
script: 
  - wget https://raw.githubusercontent.com/CSIS-iLab/india-states/master/algolia-sync.rb
  - chmod +x algolia-sync.rb
  - echo 'source \'https://rubygems.org\'\ngem "algoliasearch"' > Gemfile
  - bundle install
  - bundle exec ruby algolia-sync.rb
rvm:
 - 2.2
