language: ruby
cache: bundler
branches:
  only:
    - gh-pages
script: 
  - echo 'gem "agoliasearch"' > Gemfile
  - bundle install
  - wget https://raw.githubusercontent.com/CSIS-iLab/india-states/master/algolia-sync.rb
  - chmod +x algolia-sync.rb
  - ruby algolia-sync.rb
rvm:
 - 2.2
