---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
- type: document
  path: NETLIFY.md
  label: Build Status
  read_only: true
- type: heading
  label: DATA
- type: document
  path: _data/national-goals/wind-performance-tracker.json
  label: Wind Performance Tracker
- type: document
  path: _data/national-goals/solar-performance-tracker.json
  label: Solar Performance Tracker
- type: heading
  label: CONTENT
- type: directory
  path: ''
  label: Pages
  create: all
  match: "/*.md"
  exclude: '["/README.md","/index.md","/search.md"]'
  new_doc_ext: md
  templates:
  - page
- type: directory
  path: _analysis
  label: Analysis
  create: all
  match: "**/*"
  templates:
  - analysis
- type: directory
  path: _posts
  label: Articles
  create: all
  match: "**/*"
  templates:
  - article
- type: directory
  path: _authors
  label: Authors
  create: all
  match: "**/*"
  templates:
  - author
- type: directory
  path: _categories
  label: Categories
  create: all
  match: "**/*"
  templates:
  - categories
- type: directory
  path: _national-goals
  label: National goals
  create: all
  match: "**/*"
  templates:
  - national-goal
- type: directory
  path: _resources
  label: Resources
  create: all
  match: "**/*"
  templates:
  - resource
- type: directory
  path: _sectors
  label: Sectors
  create: all
  match: "**/*"
  templates:
  - sector
- type: directory
  path: _states
  label: States
  create: all
  match: "**/*"
  templates:
  - state
- type: directory
  path: _subsectors
  label: Subsectors
  create: all
  match: "**/*"
  templates:
  - subsector
- type: document
  path: _data/team.yaml
  label: Team
upload_dir: _uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/build:latest
  mount_path: "/opt/buildhome/repo"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
