---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: ''
  label: Pages
  create: all
  match: "/*.md"
  exclude: "/README.md"
  new_doc_ext: md
  templates:
  - resources
- type: directory
  path: _analysis
  label: Analysis
  create: all
  match: "**/*"
  templates:
  - indian-state-level-business-reforms-first-quarter-2017
- type: directory
  path: _posts
  label: Articles
  create: all
  match: "**/*"
  templates:
  - chhattisgarh-requests-center-for-funds-to-execute-the-saubhagya-initiative-in-the-state
- type: directory
  path: _authors
  label: Authors
  create: all
  match: "**/*"
  templates:
  - sarah-watson
- type: directory
  path: _national-goals
  label: National goals
  create: all
  match: "**/*"
  templates:
  - wind-performance-tracker
- type: directory
  path: _resources
  label: Resources
  create: all
  match: "**/*"
  templates:
  - bihar
- type: directory
  path: _sectors
  label: Sectors
  create: all
  match: "**/*"
  templates:
  - energy
- type: directory
  path: _states
  label: States
  create: all
  match: "**/*"
  templates:
  - arunachal-pradesh
- type: directory
  path: _subsectors
  label: Subsectors
  create: all
  match: "**/*"
  templates:
  - subsectors
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
