---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
- type: directory
  path: ''
  label: Pages
  create: all
  match: "/*.md"
  exclude: '["/README.md","/index.md","/search.md"]'
  new_doc_ext: md
  templates:
  - page
- type: directory
  path: _analysis
  label: Analysis
  create: all
  match: "**/*"
  templates:
  - analysis
- type: directory
  path: _posts
  label: Articles
  create: all
  match: "**/*"
  templates:
  - article
- type: directory
  path: _authors
  label: Authors
  create: all
  match: "**/*"
  templates:
  - author
- type: directory
  path: _national-goals
  label: National goals
  create: all
  match: "**/*"
  templates:
  - national-goal
- type: directory
  path: _resources
  label: Resources
  create: all
  match: "**/*"
  templates:
  - resource
- type: directory
  path: _sectors
  label: Sectors
  create: all
  match: "**/*"
  templates:
  - sector
- type: directory
  path: _states
  label: States
  create: all
  match: "**/*"
  templates:
  - state
- type: directory
  path: _subsectors
  label: Subsectors
  create: all
  match: "**/*"
  templates:
  - subsector
- type: document
  path: _data/team.yaml
  label: Team
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
