---
---

---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: _data
  label: Data
  create: all
  match: "**/*"
- type: directory
  path: ''
  label: Pages
  create: all
  match: "*.md"
- type: directory
  path: _analysis
  label: Analysis
  create: all
  match: "**/*"
- type: directory
  path: _posts
  label: Articles
  create: all
  match: "**/*"
- type: directory
  path: _authors
  label: Authors
  create: all
  match: "**/*"
- type: directory
  path: _national-goals
  label: National goals
  create: all
  match: "**/*"
- type: directory
  path: _resources
  label: Resources
  create: all
  match: "**/*"
- type: directory
  path: _sectors
  label: Sectors
  create: all
  match: "**/*"
- type: directory
  path: _states
  label: States
  create: all
  match: "**/*"
- type: directory
  path: _subsectors
  label: Subsectors
  create: all
  match: "**/*"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
