---
label: Sources
hide_body: false
is_partial: true
fields:
- type: field_group_list
  name: sources
  label: Sources
  fields:
  - type: text
    name: name
    label: Name
  - type: text
    name: url
    label: URL
