const states = [
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Center-State Relations',
  'Chhattisgarh',
  'Delhi',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Puducherry',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttarakhand',
  'Uttar Pradesh',
  'Union Territory of Jammu and Kashmir',
  'Union Territory of Ladakh',
  'Union Territory of Lakshadweep',
  'Union Territory of the Andaman and Nicobar Islands',
  'West Bengal',
  'Union Territory of Daman and Diu',
  'Union Territory of Chandigarh'
]
export default states
